using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ParseRgbdsObj;

namespace process_hidden_objects
{
    class Program
    {
        private static List<string> Symbols = new List<string>
        {
            "MapHS00",
            "MapHS01",
            "MapHS02",
            "MapHS03",
            "MapHS0A",
            "MapHS0D",
            "MapHS0F",
            "MapHS14",
            "MapHS17",
            "MapHS1A",
            "MapHS1B",
            "MapHS21",
            "MapHS23",
            "MapHS24",
            "MapHS27",
            "MapHS28",
            "MapHS2D",
            "MapHS33",
            "MapHS34",
            "MapHS3B",
            "MapHS3D",
            "MapHS53",
            "MapHS58",
            "MapHS60",
            "MapHS66",
            "MapHS67",
            "MapHS68",
            "MapHS6C",
            "MapHS78",
            "MapHS84",
            "MapHS87",
            "MapHS8F",
            "MapHS90",
            "MapHS91",
            "MapHS92",
            "MapHS93",
            "MapHS94",
            "MapHS95",
            "MapHS9B",
            "MapHS9F",
            "MapHSA0",
            "MapHSA1",
            "MapHSA2",
            "MapHSA5",
            "MapHSB1",
            "MapHSB5",
            "MapHSC0",
            "MapHSC2",
            "MapHSC6",
            "MapHSC7",
            "MapHSC8",
            "MapHSC9",
            "MapHSCA",
            "MapHSCF",
            "MapHSD0",
            "MapHSD1",
            "MapHSD2",
            "MapHSD3",
            "MapHSD4",
            "MapHSD5",
            "MapHSD6",
            "MapHSD7",
            "MapHSD8",
            "MapHSD9",
            "MapHSDA",
            "MapHSDB",
            "MapHSDC",
            "MapHSE2",
            "MapHSE3",
            "MapHSE4",
            "MapHSE9",
            "MapHSEA",
            "MapHSEB",
            "MapHSF4",
        };

        private static Dictionary<int, string> MapNames = new Dictionary<int, string>
        {
            {1, "PalletTown"},
            {2, "ViridianCity"},
            {3, "PewterCity"},
            {4, "CeruleanCity"},
            {5, "LavenderTown"},
            {6, "VermilionCity"},
            {7, "CeladonCity"},
            {8, "FuchsiaCity"},
            {9, "CinnabarIsland"},
            {10, "IndigoPlateau"},
            {11, "SaffronCity"},
            {12, "UnusedMap"},
            {13, "Route1"},
            {14, "Route2"},
            {15, "Route3"},
            {16, "Route4"},
            {17, "Route5"},
            {18, "Route6"},
            {19, "Route7"},
            {20, "Route8"},
            {21, "Route9"},
            {22, "Route10"},
            {23, "Route11"},
            {24, "Route12"},
            {25, "Route13"},
            {26, "Route14"},
            {27, "Route15"},
            {28, "Route16"},
            {29, "Route17"},
            {30, "Route18"},
            {31, "Route19"},
            {32, "Route20"},
            {33, "Route21"},
            {34, "Route22"},
            {35, "Route23"},
            {36, "Route24"},
            {37, "Route25"},
            {38, "RedsHouse1F"},
            {39, "RedsHouse2F"},
            {40, "BluesHouse"},
            {41, "OaksLab"},
            {42, "ViridianPokecenter"},
            {43, "ViridianMart"},
            {44, "School"},
            {45, "ViridianHouse"},
            {46, "ViridianGym"},
            {47, "DiglettsCaveRoute2"},
            {48, "ViridianForestExit"},
            {49, "Route2House"},
            {50, "Route2Gate"},
            {51, "ViridianForestEntrance"},
            {52, "ViridianForest"},
            {53, "Museum1F"},
            {54, "Museum2F"},
            {55, "PewterGym"},
            {56, "PewterHouse1"},
            {57, "PewterMart"},
            {58, "PewterHouse2"},
            {59, "PewterPokecenter"},
            {60, "MtMoon1"},
            {61, "MtMoon2"},
            {62, "MtMoon3"},
            {63, "CeruleanHouseTrashed"},
            {64, "CeruleanHouse1"},
            {65, "CeruleanPokecenter"},
            {66, "CeruleanGym"},
            {67, "BikeShop"},
            {68, "CeruleanMart"},
            {69, "MtMoonPokecenter"},
            {70, "CeruleanHouseTrashedCopy"},
            {71, "Route5Gate"},
            {72, "UndergroundPathEntranceRoute5"},
            {73, "DayCareM"},
            {74, "Route6Gate"},
            {75, "UndergroundPathEntranceRoute6"},
            {76, "UndergroundPathEntranceRoute6Copy"},
            {77, "Route7Gate"},
            {78, "UndergroundPathEntranceRoute7"},
            {79, "UndergroundPathEntranceRoute7Copy"},
            {80, "Route8Gate"},
            {81, "UndergroundPathEntranceRoute8"},
            {82, "RockTunnelPokecenter"},
            {83, "RockTunnel1"},
            {84, "PowerPlant"},
            {85, "Route11Gate"},
            {86, "DiglettsCaveEntranceRoute11"},
            {87, "Route11GateUpstairs"},
            {88, "Route12Gate"},
            {89, "BillsHouse"},
            {90, "VermilionPokecenter"},
            {91, "FanClub"},
            {92, "VermilionMart"},
            {93, "VermilionGym"},
            {94, "VermilionHouse1"},
            {95, "VermilionDock"},
            {96, "SSAnne1"},
            {97, "SSAnne2"},
            {98, "SSAnne3"},
            {99, "SSAnne4"},
            {100, "SSAnne5"},
            {101, "SSAnne6"},
            {102, "SSAnne7"},
            {103, "SSAnne8"},
            {104, "SSAnne9"},
            {105, "SSAnne10"},
            {106, "UnusedMap"},
            {107, "UnusedMap"},
            {108, "UnusedMap"},
            {109, "VictoryRoad1"},
            {110, "UnusedMap"},
            {111, "UnusedMap"},
            {112, "UnusedMap"},
            {113, "UnusedMap"},
            {114, "Lance"},
            {115, "UnusedMap"},
            {116, "UnusedMap"},
            {117, "UnusedMap"},
            {118, "UnusedMap"},
            {119, "HallofFameRoom"},
            {120, "UndergroundPathNS"},
            {121, "Gary"},
            {122, "UndergroundPathWE"},
            {123, "CeladonMart1"},
            {124, "CeladonMart2"},
            {125, "CeladonMart3"},
            {126, "CeladonMart4"},
            {127, "CeladonMartRoof"},
            {128, "CeladonMartElevator"},
            {129, "CeladonMansion1"},
            {130, "CeladonMansion2"},
            {131, "CeladonMansion3"},
            {132, "CeladonMansion4"},
            {133, "CeladonMansion5"},
            {134, "CeladonPokecenter"},
            {135, "CeladonGym"},
            {136, "CeladonGameCorner"},
            {137, "CeladonMart5"},
            {138, "CeladonPrizeRoom"},
            {139, "CeladonDiner"},
            {140, "CeladonHouse"},
            {141, "CeladonHotel"},
            {142, "LavenderPokecenter"},
            {143, "PokemonTower1"},
            {144, "PokemonTower2"},
            {145, "PokemonTower3"},
            {146, "PokemonTower4"},
            {147, "PokemonTower5"},
            {148, "PokemonTower6"},
            {149, "PokemonTower7"},
            {150, "LavenderHouse1"},
            {151, "LavenderMart"},
            {152, "LavenderHouse2"},
            {153, "FuchsiaMart"},
            {154, "FuchsiaHouse1"},
            {155, "FuchsiaPokecenter"},
            {156, "FuchsiaHouse2"},
            {157, "SafariZoneEntrance"},
            {158, "FuchsiaGym"},
            {159, "FuchsiaMeetingRoom"},
            {160, "SeafoamIslands2"},
            {161, "SeafoamIslands3"},
            {162, "SeafoamIslands4"},
            {163, "SeafoamIslands5"},
            {164, "VermilionHouse2"},
            {165, "FuchsiaHouse3"},
            {166, "Mansion1"},
            {167, "CinnabarGym"},
            {168, "Lab1"},
            {169, "Lab2"},
            {170, "Lab3"},
            {171, "Lab4"},
            {172, "CinnabarPokecenter"},
            {173, "CinnabarMart"},
            {174, "CinnabarMartCopy"},
            {175, "IndigoPlateauLobby"},
            {176, "CopycatsHouse1F"},
            {177, "CopycatsHouse2F"},
            {178, "FightingDojo"},
            {179, "SaffronGym"},
            {180, "SaffronHouse1"},
            {181, "SaffronMart"},
            {182, "SilphCo1"},
            {183, "SaffronPokecenter"},
            {184, "SaffronHouse2"},
            {185, "Route15Gate"},
            {186, "Route15GateUpstairs"},
            {187, "Route16Gate"},
            {188, "Route16GateUpstairs"},
            {189, "Route16House"},
            {190, "Route12House"},
            {191, "Route18Gate"},
            {192, "Route18GateUpstairs"},
            {193, "SeafoamIslands1"},
            {194, "Route22Gate"},
            {195, "VictoryRoad2"},
            {196, "Route12GateUpstairs"},
            {197, "VermilionHouse3"},
            {198, "DiglettsCave"},
            {199, "VictoryRoad3"},
            {200, "RocketHideout1"},
            {201, "RocketHideout2"},
            {202, "RocketHideout3"},
            {203, "RocketHideout4"},
            {204, "RocketHideoutElevator"},
            {205, "UnusedMap"},
            {206, "UnusedMap"},
            {207, "UnusedMap"},
            {208, "SilphCo2"},
            {209, "SilphCo3"},
            {210, "SilphCo4"},
            {211, "SilphCo5"},
            {212, "SilphCo6"},
            {213, "SilphCo7"},
            {214, "SilphCo8"},
            {215, "Mansion2"},
            {216, "Mansion3"},
            {217, "Mansion4"},
            {218, "SafariZoneEast"},
            {219, "SafariZoneNorth"},
            {220, "SafariZoneWest"},
            {221, "SafariZoneCenter"},
            {222, "SafariZoneRestHouse1"},
            {223, "SafariZoneSecretHouse"},
            {224, "SafariZoneRestHouse2"},
            {225, "SafariZoneRestHouse3"},
            {226, "SafariZoneRestHouse4"},
            {227, "UnknownDungeon2"},
            {228, "UnknownDungeon3"},
            {229, "UnknownDungeon1"},
            {230, "NameRater"},
            {231, "CeruleanHouse2"},
            {232, "UnusedMap"},
            {233, "RockTunnel2"},
            {234, "SilphCo9"},
            {235, "SilphCo10"},
            {236, "SilphCo11"},
            {237, "SilphCoElevator"},
            {238, "UnusedMap"},
            {239, "UnusedMap"},
            {240, "TradeCenter"},
            {241, "Colosseum"},
            {242, "UnusedMap"},
            {243, "UnusedMap"},
            {244, "UnusedMap"},
            {245, "UnusedMap"},
            {246, "Lorelei"},
            {247, "Bruno"},
            {248, "Agatha"},
        };

        static void Main(string[] args)
        {
            var parser = new ObjParser("main_red.o");
            foreach (var symbol in Symbols)
            {
                var data = parser.CopySymbolData(symbol, 256);
                int map = -1;
                for (int i = 0;; i += 3)
                {
                    if (map < 0)
                        map = data[i];
                    else if (data[i] != map)
                        break;
                    var visible = data[i + 2] == 0x11 ? "false" : (data[i + 2] == 0x15 ? "true" : "null");
                    Console.WriteLine($"{symbol},{MapNames[map + 1]},{data[i + 1] - 1},{visible}");
                }
            }
        }
    }
}
