#pragma once

#include "ItemData.h"

namespace CppRed{

#define DECLARE_ITEM_FUNCTION(name) ItemUseResult name(const ItemData &item_used, Game &game, PlayerCharacter &user, bool from_battle)

DECLARE_ITEM_FUNCTION(ItemUseBait);
DECLARE_ITEM_FUNCTION(ItemUseBall);
DECLARE_ITEM_FUNCTION(ItemUseBicycle);
DECLARE_ITEM_FUNCTION(ItemUseCardKey);
DECLARE_ITEM_FUNCTION(ItemUseCoinCase);
DECLARE_ITEM_FUNCTION(ItemUseDireHit);
DECLARE_ITEM_FUNCTION(ItemUseEscapeRope);
DECLARE_ITEM_FUNCTION(ItemUseEvoStone);
DECLARE_ITEM_FUNCTION(ItemUseGoodRod);
DECLARE_ITEM_FUNCTION(ItemUseGuardSpec);
DECLARE_ITEM_FUNCTION(ItemUseItemfinder);
DECLARE_ITEM_FUNCTION(ItemUseMaxRepel);
DECLARE_ITEM_FUNCTION(ItemUseMedicine);
DECLARE_ITEM_FUNCTION(ItemUsePotion);
DECLARE_ITEM_FUNCTION(ItemUseOaksParcel);
DECLARE_ITEM_FUNCTION(ItemUseOldRod);
DECLARE_ITEM_FUNCTION(ItemUsePokedex);
DECLARE_ITEM_FUNCTION(ItemUsePokedoll);
DECLARE_ITEM_FUNCTION(ItemUsePokeflute);
DECLARE_ITEM_FUNCTION(ItemUsePPRestore);
DECLARE_ITEM_FUNCTION(ItemUsePPUp);
DECLARE_ITEM_FUNCTION(ItemUseRepel);
DECLARE_ITEM_FUNCTION(ItemUseRock);
DECLARE_ITEM_FUNCTION(ItemUseSuperRepel);
DECLARE_ITEM_FUNCTION(ItemUseSuperRod);
DECLARE_ITEM_FUNCTION(ItemUseSurfboard);
DECLARE_ITEM_FUNCTION(ItemUseTownMap);
DECLARE_ITEM_FUNCTION(ItemUseVitamin);
DECLARE_ITEM_FUNCTION(ItemUseXAccuracy);
DECLARE_ITEM_FUNCTION(ItemUseXStat);
DECLARE_ITEM_FUNCTION(UnusableItem);
DECLARE_ITEM_FUNCTION(ItemUseHm);
DECLARE_ITEM_FUNCTION(ItemUseTm);

}
